repositoryUrl: https://github.com/kesav21/go-lambda-builder.git
branches:
- main
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "@semantic-release/changelog"
- - "@semantic-release/git"
  - assets:
    - CHANGELOG.md
