repositoryUrl: https://github.com/kesav21/go-lambda-builder.git
branches:
- main
- fix/release-binaries
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "@semantic-release/changelog"
- - "@semantic-release/git"
  - assets:
    - CHANGELOG.md
- - "@semantic-release/github"
  - assets:
    - "*.zip"
- - "@semantic-release/exec"
  - verifyReleaseCmd: |
      echo ${nextRelease.version} >version
