name: Release

on:
  push:
    branches:
    - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Release
      run: |
        npm install
        npx semantic-release
