name: Test

on: push

jobs:
  build-lambdas:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3.1.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Build Lambdas
      run: |
        ls -la
        go build
        echo
        ls -la
        mv builder test/lambdas
        cd test/lambdas
        echo
        ls -la
        echo
        ./builder
