name: Test

on: push

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  build-builder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3.1.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Build Builder
      run: |
        go build

    - name: Archive Builder
      uses: actions/upload-artifact@v3
      with:
        name: builder
        path: builder

    - name: Remove test/signed/testLambda2
      run: |
        aws s3 rm s3://kesav-go-lambda-builder-test/test/signed/testLambda2.zip

  build-lambdas:
    runs-on: ubuntu-latest
    needs:
    - build-builder
    strategy:
      matrix:
        instance: [0,1]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3.1.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Download Builder
      uses: actions/download-artifact@v3
      with:
        name: builder

    - name: Run Builder
      run: |
        echo matrix instance ${{ matrix.instance }}
        echo matrix ${{ matrix }}
        chmod +x builder
        mv builder test/lambdas
        cd test/lambdas
        ./builder \
            -bucket=kesav-go-lambda-builder-test \
            -unsigned-prefix=test/unsigned \
            -staging-prefix=test/staging \
            -signed-prefix=test/signed \
            -signing-profile=main \
            -no-update-functions \
            -force \
            -instance=${{ matrix.instance }} \
            -num-instances=2 \
        # aws s3 ls --recursive kesav-go-lambda-builder-test

  clean-builder:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
    - build-builder
    - build-lambdas
    steps:
    - name: Delete Builder
      uses: geekyeggo/delete-artifact@v1
      with:
        name: builder

    # - name: Run Builder with -no-copy-signed
    #   run: |
    #     cd test/lambdas
    #     ./builder \
    #         -bucket=kesav-go-lambda-builder-test \
    #         -unsigned-prefix=test/unsigned \
    #         -staging-prefix=test/staging \
    #         -signed-prefix=test/signed \
    #         -signing-profile=main \
    #         -force \
    #         -no-copy-signed
    #     aws s3 ls --recursive kesav-go-lambda-builder-test

