name: Test

jobs:
  build-lambdas:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3.1.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Build Lambdas
      run: |
        echo hello world
