name: Test

on: push

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  build-lambdas:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3.1.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Build Builder
      run: |
        go build
        mv builder test/lambdas

    - name: Remove test/signed/testLambda2
      run: |
        aws s3 rm s3://kesav-go-lambda-builder-test/test/signed/testLambda2.zip

    - name: Run Builder
      run: |
        cd test/lambdas
        ./builder \
            -bucket=kesav-go-lambda-builder-test \
            -unsigned-prefix=test/unsigned \
            -staging-prefix=test/staging \
            -signed-prefix=test/signed \
            -signing-profile=main \
            -no-update-functions
        # aws s3 ls --recursive kesav-go-lambda-builder-test

    # - name: Run Builder with -no-copy-signed
    #   run: |
    #     cd test/lambdas
    #     ./builder \
    #         -bucket=kesav-go-lambda-builder-test \
    #         -unsigned-prefix=test/unsigned \
    #         -staging-prefix=test/staging \
    #         -signed-prefix=test/signed \
    #         -signing-profile=main \
    #         -force \
    #         -no-copy-signed
    #     aws s3 ls --recursive kesav-go-lambda-builder-test

