name: Test

on: push

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Remove test/signed/testLambda2
      run: |
        aws s3 rm s3://kesav-go-lambda-builder-test/test/signed/testLambda2.zip

  build-lambdas:
    runs-on: ubuntu-latest
    needs:
    - build-builder
    strategy:
      matrix:
        instance: [0,1,2,3,4,5,6,7,8,9]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3.1.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Build Builder
      run: |
        go build

    - name: Run Builder
      run: |
        chmod +x builder
        mv builder test/lambdas
        cd test/lambdas
        ./builder \
            -bucket=kesav-go-lambda-builder-test \
            -unsigned-prefix=test/unsigned \
            -staging-prefix=test/staging \
            -signed-prefix=test/signed \
            -signing-profile=main \
            -no-update-functions \
            -force \
            -instance=${{ strategy.job-index }} \
            -num-instances=${{ strategy.job-total }} \


