name: Test

on: push

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  build-lambdas:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3.1.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Build Lambdas
      run: |
        go build
        mv builder test/lambdas
        cd test/lambdas
        ./builder \
            -bucket=kesav-go-lambda-builder-test \
            -unsigned-prefix=test/unsigned \
            -staging-prefix=test/staging \
            -signed-prefix=test/signed \
            -signing-profile=main

